import { Appointment, AppointmentType, Location, Patient, Provider, Form, FormEncounter, FormResource, FormSubmission, Field, FieldAnswer, FieldOption, Encounter, EncounterType, Obs, Order, OrderFrequency, OrderRoute, OrderType, OrderUnit, Concept, ConceptAnswer, ConceptClass, ConceptDatatype, ConceptMap, ConceptName, ConceptNumeric, ConceptProposal, ConceptSet, ConceptSource, ConceptWord, Resource, BlogPost, BlogPostTag, BlogPostTagArrow, BlogPostAuthor, SpaceTimeCoordinates } from "./entities";

const Entities = {Appointment, 
    AppointmentType, 
    Location, 
    Patient, 
    Provider, 
    Form, 
    FormEncounter, 
    FormResource, 
    FormSubmission, 
    Field, 
    FieldAnswer, 
    FieldOption, 
    Encounter, 
    EncounterType, 
    Obs, 
    Order, 
    OrderFrequency, 
    OrderRoute, 
    OrderType, 
    OrderUnit, 
    Concept, 
    ConceptAnswer, 
    ConceptClass, 
    ConceptDatatype, 
    ConceptMap, 
    ConceptName, 
    ConceptNumeric, 
    ConceptProposal, 
    ConceptSet, 
    ConceptSource, 
    ConceptWord, 
    Resource, 
    BlogPost, 
    BlogPostTag, 
    BlogPostTagArrow, 
    BlogPostAuthor, 
    SpaceTimeCoordinates} as const;

export type EntitiesType = typeof Entities;
export type NTTKey = keyof EntitiesType;
