version: "3.9"

env_file: ../.env

services:
  paradedb:
    image: paradedb/paradedb:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - ./data:/var/lib/postgresql/data

  hono:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "8080:8080"
    depends_on:
      - paradedb
